apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  MYSQL_DATABASE: recipes
  MYSQL_USER: recipeuser
  MYSQL_PASSWORD: recipepassword
  MYSQL_ROOT_PASSWORD: rootpassword
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE USER IF NOT EXISTS 'recipeuser'@'%' IDENTIFIED BY 'recipepassword';
    GRANT ALL PRIVILEGES ON recipes.* TO 'recipeuser'@'%';
    FLUSH PRIVILEGES;
